import { Match } from '@/types';

export const MATCHES_DATA: Match[] = [
  {
    id: '1',
    teamA: 'Manchester United',
    teamB: 'Chelsea',
    time: 'Today, 8:00 PM',
    status: 'UPCOMING',
    format: 'EPL',
    date: '2025-09-04T20:00:00Z',
    venue: 'Old Trafford, Manchester',
    players: [
      // Manchester United Players
      { id: 101, name: 'A. Onana', team: 'Manchester United', role: 'GK', credit: 9.0 },
      { id: 102, name: 'D. Dalot', team: 'Manchester United', role: 'DEF', credit: 8.5 },
      { id: 103, name: 'L. Martínez', team: 'Manchester United', role: 'DEF', credit: 8.5 },
      { id: 104, name: 'H. Maguire', team: 'Manchester United', role: 'DEF', credit: 8.0 },
      { id: 105, name: 'Casemiro', team: 'Manchester United', role: 'MID', credit: 9.5 },
      { id: 106, name: 'B. Fernandes', team: 'Manchester United', role: 'MID', credit: 10.5 },
      { id: 107, name: 'S. McTominay', team: 'Manchester United', role: 'MID', credit: 8.5 },
      { id: 108, name: 'M. Rashford', team: 'Manchester United', role: 'FWD', credit: 10.0 },
      { id: 109, name: 'R. Højlund', team: 'Manchester United', role: 'FWD', credit: 9.0 },
      { id: 110, name: 'Antony', team: 'Manchester United', role: 'FWD', credit: 8.5 },
      { id: 111, name: 'A. Garnacho', team: 'Manchester United', role: 'MID', credit: 8.0 },

      // Chelsea Players
      { id: 201, name: 'R. Sánchez', team: 'Chelsea', role: 'GK', credit: 9.0 },
      { id: 202, name: 'R. James', team: 'Chelsea', role: 'DEF', credit: 9.0 },
      { id: 203, name: 'T. Silva', team: 'Chelsea', role: 'DEF', credit: 8.5 },
      { id: 204, name: 'B. Chilwell', team: 'Chelsea', role: 'DEF', credit: 8.5 },
      { id: 205, name: 'E. Fernández', team: 'Chelsea', role: 'MID', credit: 10.0 },
      { id: 206, name: 'M. Caicedo', team: 'Chelsea', role: 'MID', credit: 9.5 },
      { id: 207, name: 'C. Palmer', team: 'Chelsea', role: 'MID', credit: 9.0 },
      { id: 208, name: 'R. Sterling', team: 'Chelsea', role: 'FWD', credit: 9.5 },
      { id: 209, name: 'N. Jackson', team: 'Chelsea', role: 'FWD', credit: 9.0 },
      { id: 210, name: 'M. Mudryk', team: 'Chelsea', role: 'FWD', credit: 8.5 },
      { id: 211, name: 'C. Gallagher', team: 'Chelsea', role: 'MID', credit: 8.0 },
    ],
  },
  {
    id: '2',
    teamA: 'Liverpool',
    teamB: 'Arsenal',
    time: 'Tomorrow, 5:00 PM',
    status: 'UPCOMING',
    format: 'EPL',
    date: '2025-09-05T17:00:00Z',
    venue: 'Anfield, Liverpool',
    players: [
      // Liverpool Players
      { id: 301, name: 'Alisson B.', team: 'Liverpool', role: 'GK', credit: 10.0 },
      { id: 302, name: 'V. van Dijk', team: 'Liverpool', role: 'DEF', credit: 9.5 },
      { id: 303, name: 'T. Alexander-Arnold', team: 'Liverpool', role: 'DEF', credit: 9.0 },
      { id: 304, name: 'A. Robertson', team: 'Liverpool', role: 'DEF', credit: 8.5 },
      { id: 305, name: 'D. Szoboszlai', team: 'Liverpool', role: 'MID', credit: 9.5 },
      { id: 306, name: 'A. Mac Allister', team: 'Liverpool', role: 'MID', credit: 9.0 },
      { id: 307, name: 'M. Salah', team: 'Liverpool', role: 'FWD', credit: 11.0 },
      { id: 308, name: 'D. Núñez', team: 'Liverpool', role: 'FWD', credit: 9.5 },
      { id: 309, name: 'L. Díaz', team: 'Liverpool', role: 'FWD', credit: 9.0 },
      { id: 310, name: 'C. Gakpo', team: 'Liverpool', role: 'FWD', credit: 8.5 },
      { id: 311, name: 'H. Elliott', team: 'Liverpool', role: 'MID', credit: 8.0 },

      // Arsenal Players
      { id: 401, name: 'D. Raya', team: 'Arsenal', role: 'GK', credit: 9.0 },
      { id: 402, name: 'W. Saliba', team: 'Arsenal', role: 'DEF', credit: 9.0 },
      { id: 403, name: 'Gabriel', team: 'Arsenal', role: 'DEF', credit: 8.5 },
      { id: 404, name: 'B. White', team: 'Arsenal', role: 'DEF', credit: 8.5 },
      { id: 405, name: 'D. Rice', team: 'Arsenal', role: 'MID', credit: 10.0 },
      { id: 406, name: 'M. Ødegaard', team: 'Arsenal', role: 'MID', credit: 10.5 },
      { id: 408, name: 'G. Jesus', team: 'Arsenal', role: 'FWD', credit: 9.5 },
      { id: 409, name: 'G. Martinelli', team: 'Arsenal', role: 'FWD', credit: 9.0 },
      { id: 410, name: 'K. Havertz', team: 'Arsenal', role: 'MID', credit: 8.5 },
      { id: 411, name: 'L. Trossard', team: 'Arsenal', role: 'MID', credit: 8.0 },
    ],
  },
  {
    id: '3',
    teamA: 'Tottenham',
    teamB: 'Barcelona',
    time: 'September 6, 6:00 PM',
    status: 'UPCOMING',
    format: 'EPL/La Liga',
    date: '2025-09-06T18:00:00Z',
    venue: 'Tottenham Hotspur Stadium, London',
    players: [
      // Tottenham Players
      { id: 501, name: 'P. Gazzaniga', team: 'Tottenham', role: 'GK', credit: 8.5 },
      { id: 502, name: 'S. Tanganga', team: 'Tottenham', role: 'DEF', credit: 8.0 },
      { id: 503, name: 'E. Dier', team: 'Tottenham', role: 'DEF', credit: 8.5 },
      { id: 504, name: 'S. Romero', team: 'Tottenham', role: 'DEF', credit: 8.0 },
      { id: 505, name: 'H. Højbjerg', team: 'Tottenham', role: 'MID', credit: 9.0 },
      { id: 506, name: 'P. Højbjerg', team: 'Tottenham', role: 'MID', credit: 8.5 },
      { id: 507, name: 'H. Kane', team: 'Tottenham', role: 'FWD', credit: 11.0 },
      { id: 508, name: 'S. Son', team: 'Tottenham', role: 'FWD', credit: 10.5 },
    ],
  },
  {
    id: '4',
    teamA: 'Real Madrid',
    teamB: 'Barcelona',
    time: 'September 7, 9:00 PM',
    status: 'UPCOMING',
    format: 'La Liga',
    date: '2025-09-07T21:00:00Z',
    venue: 'Santiago Bernabéu, Madrid',
    players: [
      // Real Madrid Players
      { id: 601, name: 'T. Courtois', team: 'Real Madrid', role: 'GK', credit: 10.0 },
      { id: 602, name: 'D. Alaba', team: 'Real Madrid', role: 'DEF', credit: 9.0 },
      { id: 603, name: 'E. Militão', team: 'Real Madrid', role: 'DEF', credit: 8.5 },
      { id: 604, name: 'F. Mendy', team: 'Real Madrid', role: 'DEF', credit: 8.5 },
      { id: 605, name: 'L. Modrić', team: 'Real Madrid', role: 'MID', credit: 10.0 },
      { id: 606, name: 'T. Kroos', team: 'Real Madrid', role: 'MID', credit: 10.0 },
      { id: 607, name: 'V. Vinícius Jr.', team: 'Real Madrid', role: 'FWD', credit: 10.5 },
      { id: 608, name: 'B. Díaz', team: 'Real Madrid', role: 'FWD', credit: 9.5 },

      // Barcelona Players
      { id: 701, name: 'M. ter Stegen', team: 'Barcelona', role: 'GK', credit: 10.0 },
      { id: 702, name: 'J. Koundé', team: 'Barcelona', role: 'DEF', credit: 8.5 },
      { id: 703, name: 'A. Christensen', team: 'Barcelona', role: 'DEF', credit: 8.5 },
      { id: 704, name: 'J. Alba', team: 'Barcelona', role: 'DEF', credit: 8.5 },
      { id: 705, name: 'F. de Jong', team: 'Barcelona', role: 'MID', credit: 9.5 },
      { id: 706, name: 'P. Gavi', team: 'Barcelona', role: 'MID', credit: 9.0 },
      { id: 707, name: 'R. Lewandowski', team: 'Barcelona', role: 'FWD', credit: 11.0 },
      { id: 708, name: 'O. Dembélé', team: 'Barcelona', role: 'FWD', credit: 10.0 },
    ],
  },
];
